version: '3'
services:
  db:
    container_name: postgres-db-container
    image: "postgres:13"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "webjump"
      POSTGRES_PASSWORD: "secret"
      POSTGRES_DB: "webjump_pg_db"
    volumes:
      - ./.docker/db_data:/var/lib/postgresql/data
